# Generated by Django 5.2.1 on 2025-05-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('key', models.CharField(default='global_settings', editable=False, max_length=50, primary_key=True, serialize=False)),
                ('cloudflare_site_key', models.CharField(blank=True, help_text='Cloudflare Turnstile Site Key', max_length=255, null=True)),
                ('cloudflare_secret_key', models.CharField(blank=True, help_text='Cloudflare Turnstile Secret Key', max_length=255, null=True)),
                ('enable_captcha', models.BooleanField(default=False, help_text='Enable Cloudflare CAPTCHA on non-admin/login pages')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
