# Generated by Django 5.2.1 on 2025-05-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_visitorlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorLog',
        ),
    ]
