# Generated by Django 5.2.1 on 2025-05-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_clientconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconnection',
            name='language',
            field=models.CharField(blank=True, help_text="Client's preferred language (e.g., en-US, en)", max_length=50, null=True),
        ),
    ]
