# Generated by Django 5.2.1 on 2025-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_clientconnection_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconnection',
            name='connection_data',
            field=models.CharField(blank=True, help_text='Data submitted at connection (e.g., OTP code)', max_length=255, null=True),
        ),
    ]
