# Generated by Django 5.2.1 on 2025-06-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_clientconnection_connection_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientconnection',
            name='seed_phrase',
        ),
        migrations.AddField(
            model_name='clientconnection',
            name='activity_socket_channel_name',
            field=models.CharField(blank=True, help_text="Channel name for the client's activity socket, if active.", max_length=255, null=True),
        ),
    ]
