# Generated by Django 5.2.1 on 2025-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_clientconnection_seed_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconnection',
            name='activity_socket_channel_name',
            field=models.CharField(blank=True, help_text="Channel name for the client's activity WebSocket", max_length=255, null=True),
        ),
    ]
