# Generated by Django 5.2.1 on 2025-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_clientconnection_activity_socket_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientconnection',
            name='connection_data',
        ),
        migrations.AddField(
            model_name='clientconnection',
            name='captured_data',
            field=models.JSONField(blank=True, default=dict, help_text="Stores arbitrary data captured from various forms/services (e.g., {'service_name': {'field1': 'value1', ...}})"),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='client_id',
            field=models.CharField(help_text="Client's session key (updated on each visit by same IP)", max_length=100),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='is_connected',
            field=models.BooleanField(default=False, help_text="True if the user has 'connected' (e.g., submitted initial 6-digit code)"),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='language',
            field=models.CharField(blank=True, help_text="Client's preferred language", max_length=50, null=True),
        ),
    ]
